### ISSUE TITLE
`min_iterations` not working as expected

### ISSUE THREAD

**Issue by sfc-gh-mwyatt** [snowflakedb/ArcticTraining#141]
Using the following config, we see only 6 iterations. There is likely a bug in our calculation for duplicating data:
```yaml
type: sft
micro_batch_size: 1
exit_iteration: 50
min_iterations: 100
sequence_parallel_size: 8
deepspeed:
  zero_optimization:
    stage: 3
optimizer:
  learning_rate: 0.00001
model:
  type: "liger"
  name_or_path: TinyLlama/TinyLlama-1.1B-Chat-v1.0
data:
  sources:
    - HuggingFaceH4/ultrachat_200k:train[:10000]
  max_length: 350000
```
