### ISSUE TITLE
config: support values with scientific notation

### ISSUE THREAD

**Issue by sfc-gh-sbekman** [snowflakedb/ArcticTraining#165]
Currently this config fails as it doesn't realize `5e8` is a valid int, in scientific notation.
```
deepspeed:
  zero_optimization:
    stage: 3
    reduce_bucket_size: 5e8
```

```
[rank7]: pydantic_core._pydantic_core.ValidationError: 1 validation error for DeepSpeedZeroConfig
[rank7]: reduce_bucket_size
[rank7]:   Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='10e8', input_type=str]
[rank7]:     For further information visit https://errors.pydantic.dev/2.11/v/int_parsing
```

tag: @sfc-gh-mwyatt
