### ISSUE TITLE
[feature request] add `data.cache_fs_type` config entry

### ISSUE THREAD

**Issue by sfc-gh-sbekman** [snowflakedb/ArcticTraining#87]
I added `cache_fs_type: auto` logic to automatically figure out whether the cache is on a local or shared fs and build the cache correspondingly, but I'm concerned there will be cases where it might fail and so I think we should give the user a way to override and set the type of cache fs explicitly, so I propose this new config entry:

```
  cache_fs_type: [auto|local|shared]
```
which would map like:
```
data:
  use_data_cache: true
  cache_processed_data: true
  cache_dir: /data-fast/data-cache/stas
  cache_fs_type: [auto|local|shared]
```
with `auto` being the default.
