### ISSUE TITLE
[feature request] dynamic config that can self-reference

### ISSUE THREAD

**Issue by sfc-gh-sbekman** [snowflakedb/ArcticTraining#94]
The idea is to be able to re-use earlier config entries to construct new ones
```
sequence_parallel_size: 8
wandb:
[...]
  name: "dp1-sp{$sequence_parallel_size}-liger"
```
and it could be a sub-config referral:
```
foo:
   bar: 5
wandb:
  name: "dp1-sp{$foo.bar}-liger"
```
I think megaconf and a few other config systems support that.

This would allow for more automation and will reduce annotation mistakes when running multiple experiments with varying parameters.
